spring:
  application:
    name: system-management
  config:
    import: optional:application-secret.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/system_management
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret:
  expiration-time: 3600000